version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=zhubot
      - POSTGRES_PASSWORD=zhubot
      - POSTGRES_DB=zhubot
    volumes:
      - ./data:/var/lib/postgresql
